// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Question struct {
	ID              int64    `json:"id"`
	Question        string   `json:"question"`
	PossibleAnswers []string `json:"possibleAnswers"`
	CorrectAnswer   string   `json:"correctAnswer"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
}

type UserQuizQuestion struct {
	ID            int64         `json:"id"`
	UserQuizRunID pgtype.Int8   `json:"userQuizRunId"`
	Question      string        `json:"question"`
	WrongAnswers  []string      `json:"wrongAnswers"`
	CorrectAnswer string        `json:"correctAnswer"`
	GivenAnswer   pgtype.Text   `json:"givenAnswer"`
	TimeNeeded    pgtype.Float8 `json:"timeNeeded"`
}

type UserQuizRun struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
